if(other.yvel>=0)
{
	play_sound(soundbounce,.25)
	if(other.anim=2)
	{
		other.anim=0
		other.charge=0
	}
	instance_create_depth(other.x,other.y+32,depth-1,particle,{image_xscale:choose(-1,1)})
	other.yvel=-20
	squishvel=.25
	if(other.jumps!=other.maxjumps)
	{
		other.jumps=other.maxjumps
		other.flash=6
	}
	image_xscale=1
	image_yscale=1
}