if(jumps!=maxjumps)
{
	shader_set(rgb_replacement)
	shader_set_uniform_f(upixelW,texelW);
	shader_set_uniform_f(upixelH,texelH);
	shader_set_uniform_f(uniformr,red[0],red[1],red[2],1.0);
	shader_set_uniform_f(uniformg,green[0],green[1],green[2],1.0);
	shader_set_uniform_f(uniformb,blue[0],blue[1],blue[2],1.0);
	draw_sprite_ext(JumpsSpr,jumps,x-xvel,y-yvel,image_xscale,1,0,c_white,1)
	shader_reset()
}
draw_set_font(NORMALFONT)
draw_set_halign(fa_left)
draw_set_valign(fa_center)
draw_set_color(c_black)
draw_text(0,684,points)
draw_text(0,692,points)
draw_set_color(c_white)
draw_text(0,688,points)