draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_set_font(BIGFONT)
draw_set_color(c_white)	
draw_text((room_width/2),(room_height/2)-64,"PAUSED")
draw_set_font(NORMALFONT)
draw_text((room_width/2),(room_height/2),"Press Enter/Select to return to title.")
draw_text((room_width/2),(room_height/2)+64,"Press JUMP+BOOST to reset stage.")